spring.application.name=pdsa_backend
server.servlet.context-path=/pdsa
server.port=8081

#database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/pdsa_games
spring.datasource.username=root
spring.datasource.password=PubuduPamod@2014